### ISSUE TITLE
Should device_added and device_removed take the same type?

### ISSUE THREAD

**Issue by 4Kaylum** [buttplugio/buttplug-py#5]
Your `ButtplugClient.device_added_handler` takes a `ButtplugClientDevice` as a param ([link](https://github.com/buttplugio/buttplug-py/blob/master/buttplug/client/client.py#L141)), and the `ButtplugClient.device_removed_handler` takes an `int` ([link](https://github.com/buttplugio/buttplug-py/blob/master/buttplug/client/client.py#L145)) referring to the device's index. It makes more sense to me personally for it to take a `ButtplugClientDevice` both times.

This would be a breaking change, but to me it makes more sense than right now. Please do say if you did this deliberately.

**Comment by DevelopmentalOctopus** [comment]
Agreed; @qdot this complicates Home Assistant integration.

A Home Assistant integration would greatly prefer using the name as an internal ID rather than an index, so the user can reference the device by (the much more stable) name when adding it to Home Assistant scripts.

This is already mostly achievable; except that `device_removed_handler`s are given an index rather than a device or name. Because the device is removed before the event is sent; it makes sense to not send the device.

Can we adjust it to report the name when deleting? or both index and name? Or to avoid breaking changes; a second `device_removed_handler` that emits the name?

**Comment by DevelopmentalOctopus** [comment]
Current workaround is to just check `ButtplugClient.devices` on every `device_removed_handler` event.
